USE im_league_tracker; 
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 1, 4, 7);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 1, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 1, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 1, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 1, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 1, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 1, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 1, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 1, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 1, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 1, 4, 1);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 1, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 1, 2, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 1, 7, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 1, 7, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 1, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 1, 2, 7);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 1, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 1, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 1, 5, 4);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 1, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 1, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 1, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 1, 2, 5);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 1, 7, 3);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 21, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 19, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 11, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 16, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 23, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 12, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 3, 2, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 17, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 3, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 11, 5, 7);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 22, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 4, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 9, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 21, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 24, 2, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 12, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 6, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 17, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 13, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 2, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 5, 5, 3);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 16, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 19, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 9, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 17, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 4, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 14, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 5, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 4, 2, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 16, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 2, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 12, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 12, 2, 1);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 9, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 23, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 9, 7, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 15, 8, 5);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 26, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 1, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 14, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 15, 8, 4);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 16, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 2, 5, 2);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 18, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 5, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 9, 3, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 13, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 12, 2, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 9, 7, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 14, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 19, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 1, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 5, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 10, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 16, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 12, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 9, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 13, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 1, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 1, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 25, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 9, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 14, 5, 7);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 23, 1, 7);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 13, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 5, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 6, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 7, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 6, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 13, 7, 7);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 5, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 20, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 19, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 8, 7, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 22, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 4, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 6, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 2, 8, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 3, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 17, 2, 7);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 2, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 16, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 2, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 7, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 7, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 20, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 8, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 10, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 6, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 6, 7, 5);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 9, 6, 5);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 12, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 18, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 17, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 17, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 22, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 8, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 1, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 18, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 11, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 5, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 14, 4, 8);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 10, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 21, 6, 1);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 17, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 20, 7, 4);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 2, 3, 5);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 25, 7, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 11, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 21, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 3, 5, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 17, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 22, 3, 5);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 3, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 19, 8, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 15, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 25, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 6, 8, 5);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 12, 2, 5);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 10, 7, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 2, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 11, 4, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 15, 3, 5);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 13, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 6, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 17, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 4, 3, 2);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 22, 4, 4);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 23, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 9, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 21, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 10, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 11, 5, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 24, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 10, 8, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 19, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 2, 5, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 2, 8, 3);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 9, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 22, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 24, 5, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 19, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 3, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 2, 7, 7);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 13, 2, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 16, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 15, 8, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 12, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 10, 7, 5);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 25, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 13, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 3, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 3, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 8, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 13, 1, 7);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 1, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 20, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 20, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 6, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 13, 3, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 16, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 6, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 23, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 3, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 14, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 19, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 21, 5, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 8, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 4, 3, 4);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 10, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 20, 4, 7);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 19, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 25, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 13, 8, 8);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 21, 2, 8);
