USE im_league_tracker; 
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 30, 4, 7);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 29, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 19, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 5, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 6, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 30, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 8, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 2, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 21, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 18, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 28, 4, 1);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 11, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 40, 2, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 39, 7, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 24, 7, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 28, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 41, 2, 7);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 21, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 40, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 40, 5, 4);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 32, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 24, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 19, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 19, 2, 5);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 17, 7, 3);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 47, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 45, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 11, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 16, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 49, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 38, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 29, 2, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 43, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 3, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 37, 5, 7);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 48, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 30, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 9, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 21, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 50, 2, 1);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 12, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 32, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 43, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 13, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 2, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 31, 5, 3);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 16, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 45, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 35, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 17, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 30, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 14, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 31, 7, 8);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 30, 2, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 16, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 2, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 12, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 38, 2, 1);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 35, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 49, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 35, 7, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 15, 8, 5);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 26, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 27, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 40, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 41, 8, 4);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 16, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 2, 5, 2);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 44, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 31, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 35, 3, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 39, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 38, 2, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 35, 7, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 14, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 19, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 1, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 5, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 36, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 16, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 12, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 9, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 39, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 1, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 27, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 25, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 35, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 40, 5, 7);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 49, 1, 7);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 13, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 31, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 6, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 33, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 32, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 13, 7, 7);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 5, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 46, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 45, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 8, 7, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 22, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 30, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 32, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 28, 8, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 3, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 17, 2, 7);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 28, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 42, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 28, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 33, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 7, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 20, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 8, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 10, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 32, 1, 6);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 6, 7, 5);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 35, 6, 5);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 38, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 44, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 43, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 43, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 48, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 34, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 1, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 18, 4, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 37, 3, 3);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 31, 5, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 40, 4, 8);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 36, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 21, 6, 1);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 43, 3, 1);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 46, 7, 4);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 28, 3, 5);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 25, 7, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 37, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 47, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 29, 5, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 17, 1, 8);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 48, 3, 5);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 29, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 19, 8, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 41, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 25, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 32, 8, 5);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 12, 2, 5);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 10, 7, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 2, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 11, 4, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 41, 3, 5);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 13, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 32, 1, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 43, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 30, 3, 2);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 22, 4, 4);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 49, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 35, 2, 6);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 21, 6, 8);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 36, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 11, 5, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 24, 6, 6);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 10, 8, 3);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 45, 7, 2);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 28, 5, 7);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 28, 8, 3);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 35, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 22, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 50, 5, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 45, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 29, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Swift Wolves', 2, 7, 7);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 39, 2, 3);
insert into Teams (name, league_played, wins, losses) values ('Raging Rhinos', 16, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 15, 8, 4);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 12, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 36, 7, 5);
insert into Teams (name, league_played, wins, losses) values ('Savage Sharks', 25, 5, 5);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 39, 8, 7);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 3, 1, 3);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 3, 2, 8);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 8, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 13, 1, 7);
insert into Teams (name, league_played, wins, losses) values ('Thunderbolts', 1, 7, 1);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 20, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 46, 6, 3);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 6, 5, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 39, 3, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 42, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 6, 6, 7);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 23, 4, 6);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 3, 1, 1);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 14, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Fierce Falcons', 19, 1, 2);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 21, 5, 3);
insert into Teams (name, league_played, wins, losses) values ('Stealthy Panthers', 8, 6, 4);
insert into Teams (name, league_played, wins, losses) values ('Blazing Bears', 4, 3, 4);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 36, 8, 2);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 46, 4, 7);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 19, 3, 6);
insert into Teams (name, league_played, wins, losses) values ('Electric Eagles', 25, 4, 5);
insert into Teams (name, league_played, wins, losses) values ('Mighty Mustangs', 39, 8, 8);
insert into Teams (name, league_played, wins, losses) values ('Golden Griffins', 47, 2, 8);
