USE im_league_tracker; 

insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Don''t forget to log your stats for tonight''s game!', '2025-11-15 16:00:00', 'sent', 1, 2, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Great game last night! Remember to log your individual stats', '2025-11-16 09:15:00', 'sent', 1, 2, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry deadline: 24 hours after game completion', '2025-11-14 10:00:00', 'sent', 1, 1, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please review and confirm your stats from last game', '2025-11-15 17:30:00', 'pending', 1, 2, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry incomplete for last game. Please complete ASAP', '2025-11-16 11:00:00', 'pending', 1, 3, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Game scheduled for tomorrow at 6 PM. Please arrive 15 minutes early for warm-up!', '2025-11-20 14:30:00', 'sent', 2, 3, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Don''t forget to log your stats for tonight''s game!', '2025-11-15 16:00:00', 'sent', 2, 1, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats from last game need review ASAP', '2025-11-18 10:30:00', 'pending', 3, 1, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Practice cancelled this week due to facility maintenance', '2025-11-10 09:00:00', 'sent', 4, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game tomorrow at 7 PM - be there 15 mins early!', '2025-11-19 08:00:00', 'sent', 5, 4, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please update your availability for next week''s games', '2025-11-22 11:00:00', 'pending', 6, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Great game last night! Remember to log your individual stats', '2025-11-16 09:15:00', 'sent', 1, 2, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Uniforms will be distributed before the game on Friday', '2025-11-17 14:00:00', 'sent', 2, 3, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Team meeting scheduled for Wednesday at 5 PM', '2025-11-12 13:30:00', 'sent', 3, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry deadline: 24 hours after game completion', '2025-11-14 10:00:00', 'sent', 4, 2, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Away game this Saturday. Carpool arrangements needed', '2025-11-21 15:00:00', 'pending', 5, 5, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Congratulations on the win! Please verify your stats are accurate', '2025-11-17 20:00:00', 'sent', 6, 4, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game time changed to 8 PM instead of 7 PM', '2025-11-18 12:00:00', 'sent', 1, 3, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Stat keeper needed for next week''s game', '2025-11-20 09:00:00', 'pending', 2, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Team photo day scheduled for next Monday', '2025-11-19 11:00:00', 'sent', 3, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please review and confirm your stats from last game', '2025-11-15 17:30:00', 'pending', 4, 2, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game location changed to Court B instead of Court A', '2025-11-16 14:00:00', 'sent', 5, 4, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('End of season party scheduled for December 15th', '2025-11-13 10:00:00', 'sent', 6, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Submit your availability for playoffs', '2025-11-22 08:00:00', 'pending', 1, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats correction needed: Please check your rebounds count', '2025-11-17 16:00:00', 'pending', 2, 1, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game cancelled due to weather. Rescheduled for next week', '2025-11-19 07:00:00', 'sent', 3, 3, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Bring water bottles and team jerseys', '2025-11-20 13:00:00', 'sent', 4, 3, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Team captain meeting tomorrow at 6 PM', '2025-11-18 15:00:00', 'sent', 5, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry incomplete for last game. Please complete ASAP', '2025-11-16 11:00:00', 'pending', 6, 4, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Playoff bracket released. Check schedule', '2025-11-21 10:00:00', 'sent', 1, NULL, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Great effort last game! Keep up the momentum', '2025-11-17 19:00:00', 'sent', 2, 1, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Equipment return after final game', '2025-11-14 12:00:00', 'sent', 3, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats verification needed before next game', '2025-11-19 14:30:00', 'pending', 4, 3, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game time confirmed: 6:30 PM sharp', '2025-11-20 08:00:00', 'sent', 5, 5, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Team dinner after the game on Friday', '2025-11-18 16:00:00', 'sent', 6, 4, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please log your stats within 48 hours of game completion', '2025-11-15 15:00:00', 'sent', 1, 2, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry deadline approaching. Please complete now', '2025-11-21 09:30:00', 'pending', 2, 1, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Bring your student ID for game check-in', '2025-11-19 12:00:00', 'sent', 3, 3, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Team practice moved to Thursday this week', '2025-11-13 11:00:00', 'sent', 4, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats review meeting scheduled for this Friday', '2025-11-17 10:00:00', 'sent', 5, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Game tomorrow. Check weather updates', '2025-11-20 07:00:00', 'sent', 6, 5, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please verify your assists count from last game', '2025-11-16 18:00:00', 'pending', 1, 2, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: End of season awards ceremony next week', '2025-11-14 14:00:00', 'sent', 2, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry incomplete. Please complete before next game', '2025-11-18 17:00:00', 'pending', 3, 1, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game location updated: Now at Field 2', '2025-11-19 13:00:00', 'sent', 4, 3, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Team bonding event this Saturday', '2025-11-12 15:00:00', 'sent', 5, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats correction: Points scored needs verification', '2025-11-17 15:30:00', 'pending', 6, 4, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Playoff game this weekend. Be ready!', '2025-11-21 11:00:00', 'sent', 1, NULL, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please update your contact information in the system', '2025-11-13 09:00:00', 'pending', 2, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry deadline: Tonight at midnight', '2025-11-18 20:00:00', 'pending', 3, 1, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Bring extra jerseys for potential jersey swap', '2025-11-20 10:00:00', 'sent', 4, 3, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game postponed. New date TBA', '2025-11-19 08:30:00', 'sent', 5, 4, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats verification needed for playoff eligibility', '2025-11-22 09:00:00', 'pending', 6, NULL, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Team meeting to discuss strategy', '2025-11-16 16:00:00', 'sent', 1, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please log your stats before the deadline', '2025-11-17 21:00:00', 'pending', 2, 1, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Game warm-up starts 30 minutes before', '2025-11-20 11:30:00', 'sent', 3, 3, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry complete. Thank you for your prompt submission', '2025-11-15 22:00:00', 'sent', 4, 2, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Check team schedule for upcoming games', '2025-11-14 16:00:00', 'sent', 5, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats correction needed: Please verify your steals count', '2025-11-18 19:00:00', 'pending', 6, 4, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Team practice mandatory this week', '2025-11-12 17:00:00', 'sent', 1, NULL, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Game stats uploaded. Please review for accuracy', '2025-11-16 20:00:00', 'sent', 2, 1, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Playoff seeding depends on accurate stats', '2025-11-21 12:00:00', 'sent', 3, NULL, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Stats entry reminder: 24 hour deadline approaching', '2025-11-19 18:00:00', 'pending', 4, 3, 'high');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Team photo session after next game', '2025-11-17 12:00:00', 'sent', 5, NULL, 'low');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Please complete your stats entry for last game', '2025-11-20 15:30:00', 'pending', 6, 5, 'medium');
insert into Reminders (message, time_sent, status, team_id, game_id, priority) values ('Reminder: Game tomorrow. Check your equipment', '2025-11-21 13:00:00', 'sent', 1, NULL, 'high');
