USE im_league_tracker; 
insert into Player_Awards (recipient, award_type, year, description) values (15, 'MVP', 2025, 'Most Valuable Player - Outstanding performance throughout the season');
insert into Player_Awards (recipient, award_type, year, description) values (42, 'Top Scorer', 2024, 'Led the league in total points scored');
insert into Player_Awards (recipient, award_type, year, description) values (78, 'Most Assists', 2025, 'Record-breaking number of assists this season');
insert into Player_Awards (recipient, award_type, year, description) values (123, 'Best Defender', 2024, 'Exceptional defensive skills and leadership');
insert into Player_Awards (recipient, award_type, year, description) values (56, 'Most Improved', 2025, 'Significant improvement from previous season');
insert into Player_Awards (recipient, award_type, year, description) values (234, 'Rookie of the Year', 2024, 'Outstanding performance in first season');
insert into Player_Awards (recipient, award_type, year, description) values (89, 'Sportsmanship Award', 2025, 'Exemplary sportsmanship and fair play');
insert into Player_Awards (recipient, award_type, year, description) values (156, 'Top Scorer', 2023, 'Highest scoring average in the league');
insert into Player_Awards (recipient, award_type, year, description) values (267, 'MVP', 2024, 'Most Valuable Player - Dominant season performance');
insert into Player_Awards (recipient, award_type, year, description) values (45, 'Most Assists', 2023, 'Led team to championship with exceptional playmaking');
insert into Player_Awards (recipient, award_type, year, description) values (178, 'Best Defender', 2025, 'Lockdown defense and key steals');
insert into Player_Awards (recipient, award_type, year, description) values (312, 'Most Improved', 2024, 'Dramatic improvement in all statistical categories');
insert into Player_Awards (recipient, award_type, year, description) values (67, 'Rookie of the Year', 2025, 'Impressive debut season with consistent performance');
insert into Player_Awards (recipient, award_type, year, description) values (189, 'Top Scorer', 2022, 'Scoring champion with highest point total');
insert into Player_Awards (recipient, award_type, year, description) values (423, 'MVP', 2023, 'Most Valuable Player - Carried team to playoffs');
insert into Player_Awards (recipient, award_type, year, description) values (98, 'Most Assists', 2024, 'Exceptional court vision and passing ability');
insert into Player_Awards (recipient, award_type, year, description) values (245, 'Best Defender', 2023, 'Defensive player of the year');
insert into Player_Awards (recipient, award_type, year, description) values (134, 'Most Improved', 2022, 'Remarkable growth and development');
insert into Player_Awards (recipient, award_type, year, description) values (356, 'Rookie of the Year', 2023, 'Outstanding first-year performance');
insert into Player_Awards (recipient, award_type, year, description) values (201, 'Top Scorer', 2025, 'Consistent scoring throughout the season');
insert into Player_Awards (recipient, award_type, year, description) values (478, 'MVP', 2022, 'Most Valuable Player - League champion');
insert into Player_Awards (recipient, award_type, year, description) values (112, 'Most Assists', 2022, 'Record-setting assist numbers');
insert into Player_Awards (recipient, award_type, year, description) values (289, 'Best Defender', 2022, 'Elite defensive presence');
insert into Player_Awards (recipient, award_type, year, description) values (367, 'Most Improved', 2023, 'Significant statistical improvement');
insert into Player_Awards (recipient, award_type, year, description) values (145, 'Rookie of the Year', 2022, 'Exceptional rookie season');
insert into Player_Awards (recipient, award_type, year, description) values (512, 'Top Scorer', 2026, 'Leading scorer in the league');
insert into Player_Awards (recipient, award_type, year, description) values (223, 'MVP', 2026, 'Most Valuable Player - Outstanding all-around play');
insert into Player_Awards (recipient, award_type, year, description) values (456, 'Most Assists', 2026, 'Playmaking excellence');
insert into Player_Awards (recipient, award_type, year, description) values (78, 'Best Defender', 2026, 'Defensive excellence and leadership');
insert into Player_Awards (recipient, award_type, year, description) values (334, 'Most Improved', 2026, 'Dramatic improvement in performance');
insert into Player_Awards (recipient, award_type, year, description) values (167, 'Rookie of the Year', 2026, 'Impressive first season');
insert into Player_Awards (recipient, award_type, year, description) values (445, 'Top Scorer', 2021, 'Scoring champion');
insert into Player_Awards (recipient, award_type, year, description) values (278, 'MVP', 2021, 'Most Valuable Player - Exceptional season');
insert into Player_Awards (recipient, award_type, year, description) values (591, 'Most Assists', 2021, 'Outstanding playmaking ability');
insert into Player_Awards (recipient, award_type, year, description) values (123, 'Best Defender', 2021, 'Elite defensive skills');
insert into Player_Awards (recipient, award_type, year, description) values (389, 'Most Improved', 2021, 'Significant development');
insert into Player_Awards (recipient, award_type, year, description) values (234, 'Rookie of the Year', 2021, 'Outstanding debut');
insert into Player_Awards (recipient, award_type, year, description) values (567, 'Top Scorer', 2020, 'Leading scorer');
insert into Player_Awards (recipient, award_type, year, description) values (345, 'MVP', 2020, 'Most Valuable Player - Championship performance');
insert into Player_Awards (recipient, award_type, year, description) values (678, 'Most Assists', 2020, 'Record-breaking assists');
insert into Player_Awards (recipient, award_type, year, description) values (212, 'Best Defender', 2020, 'Defensive player of the year');
insert into Player_Awards (recipient, award_type, year, description) values (489, 'Most Improved', 2020, 'Remarkable improvement');
insert into Player_Awards (recipient, award_type, year, description) values (156, 'Rookie of the Year', 2020, 'Exceptional rookie campaign');
insert into Player_Awards (recipient, award_type, year, description) values (723, 'Top Scorer', 2025, 'Consistent high scoring');
insert into Player_Awards (recipient, award_type, year, description) values (234, 'MVP', 2025, 'Most Valuable Player - All-star performance');
insert into Player_Awards (recipient, award_type, year, description) values (456, 'Most Assists', 2025, 'Outstanding court vision');
insert into Player_Awards (recipient, award_type, year, description) values (567, 'Best Defender', 2025, 'Lockdown defense');
insert into Player_Awards (recipient, award_type, year, description) values (189, 'Most Improved', 2025, 'Significant statistical gains');
insert into Player_Awards (recipient, award_type, year, description) values (634, 'Rookie of the Year', 2025, 'Impressive first-year stats');
insert into Player_Awards (recipient, award_type, year, description) values (345, 'Top Scorer', 2024, 'Scoring excellence');
insert into Player_Awards (recipient, award_type, year, description) values (712, 'MVP', 2024, 'Most Valuable Player - League leader');
insert into Player_Awards (recipient, award_type, year, description) values (123, 'Most Assists', 2024, 'Playmaking mastery');
insert into Player_Awards (recipient, award_type, year, description) values (456, 'Best Defender', 2024, 'Defensive dominance');
insert into Player_Awards (recipient, award_type, year, description) values (789, 'Most Improved', 2024, 'Dramatic improvement');
insert into Player_Awards (recipient, award_type, year, description) values (234, 'Rookie of the Year', 2024, 'Outstanding debut season');
insert into Player_Awards (recipient, award_type, year, description) values (567, 'Top Scorer', 2023, 'Scoring champion');
insert into Player_Awards (recipient, award_type, year, description) values (345, 'MVP', 2023, 'Most Valuable Player - Championship MVP');
insert into Player_Awards (recipient, award_type, year, description) values (678, 'Most Assists', 2023, 'Assist leader');
insert into Player_Awards (recipient, award_type, year, description) values (123, 'Best Defender', 2023, 'Defensive excellence');
insert into Player_Awards (recipient, award_type, year, description) values (456, 'Most Improved', 2023, 'Remarkable growth');
insert into Player_Awards (recipient, award_type, year, description) values (789, 'Rookie of the Year', 2023, 'Exceptional rookie performance');
insert into Player_Awards (recipient, award_type, year, description) values (234, 'Top Scorer', 2022, 'Leading scorer');
insert into Player_Awards (recipient, award_type, year, description) values (567, 'MVP', 2022, 'Most Valuable Player - All-around excellence');
insert into Player_Awards (recipient, award_type, year, description) values (345, 'Most Assists', 2022, 'Outstanding playmaking');
insert into Player_Awards (recipient, award_type, year, description) values (678, 'Best Defender', 2022, 'Elite defensive player');
insert into Player_Awards (recipient, award_type, year, description) values (123, 'Most Improved', 2022, 'Significant development');
insert into Player_Awards (recipient, award_type, year, description) values (456, 'Rookie of the Year', 2022, 'Impressive first season');

