USE im_league_tracker; 
insert into Player_Awards (recipient, award_type, year, description) values (1, 'MVP', 2026, 'Most Valuable Player - Outstanding all-around play');
insert into Player_Awards (recipient, award_type, year, description) values (2, 'Top Scorer', 2026, 'Leading scorer in the league');
insert into Player_Awards (recipient, award_type, year, description) values (3, 'Most Assists', 2026, 'Playmaking excellence');
insert into Player_Awards (recipient, award_type, year, description) values (4, 'Best Defender', 2026, 'Defensive excellence and leadership');
insert into Player_Awards (recipient, award_type, year, description) values (5, 'Most Improved', 2026, 'Dramatic improvement in performance');
insert into Player_Awards (recipient, award_type, year, description) values (6, 'Rookie of the Year', 2026, 'Impressive first season');
insert into Player_Awards (recipient, award_type, year, description) values (7, 'MVP', 2025, 'Most Valuable Player - Outstanding performance throughout the season');
insert into Player_Awards (recipient, award_type, year, description) values (8, 'Top Scorer', 2025, 'Consistent high scoring');
insert into Player_Awards (recipient, award_type, year, description) values (9, 'Most Assists', 2025, 'Outstanding court vision');
insert into Player_Awards (recipient, award_type, year, description) values (10, 'Best Defender', 2025, 'Lockdown defense and key steals');
insert into Player_Awards (recipient, award_type, year, description) values (11, 'Most Improved', 2025, 'Significant improvement from previous season');
insert into Player_Awards (recipient, award_type, year, description) values (12, 'Rookie of the Year', 2025, 'Impressive debut season with consistent performance');
insert into Player_Awards (recipient, award_type, year, description) values (13, 'Sportsmanship Award', 2025, 'Exemplary sportsmanship and fair play');
insert into Player_Awards (recipient, award_type, year, description) values (14, 'MVP', 2024, 'Most Valuable Player - Dominant season performance');
insert into Player_Awards (recipient, award_type, year, description) values (15, 'Top Scorer', 2024, 'Led the league in total points scored');
insert into Player_Awards (recipient, award_type, year, description) values (16, 'Most Assists', 2024, 'Exceptional court vision and passing ability');
insert into Player_Awards (recipient, award_type, year, description) values (17, 'Best Defender', 2024, 'Exceptional defensive skills and leadership');
insert into Player_Awards (recipient, award_type, year, description) values (18, 'Most Improved', 2024, 'Dramatic improvement in all statistical categories');
insert into Player_Awards (recipient, award_type, year, description) values (19, 'Rookie of the Year', 2024, 'Outstanding performance in first season');
insert into Player_Awards (recipient, award_type, year, description) values (20, 'MVP', 2023, 'Most Valuable Player - Carried team to playoffs');
insert into Player_Awards (recipient, award_type, year, description) values (21, 'Top Scorer', 2023, 'Highest scoring average in the league');
insert into Player_Awards (recipient, award_type, year, description) values (22, 'Most Assists', 2023, 'Led team to championship with exceptional playmaking');
insert into Player_Awards (recipient, award_type, year, description) values (23, 'Best Defender', 2023, 'Defensive player of the year');
insert into Player_Awards (recipient, award_type, year, description) values (24, 'Most Improved', 2023, 'Significant statistical improvement');
insert into Player_Awards (recipient, award_type, year, description) values (25, 'Rookie of the Year', 2023, 'Outstanding first-year performance');
insert into Player_Awards (recipient, award_type, year, description) values (26, 'MVP', 2022, 'Most Valuable Player - League champion');
insert into Player_Awards (recipient, award_type, year, description) values (27, 'Top Scorer', 2022, 'Scoring champion with highest point total');
insert into Player_Awards (recipient, award_type, year, description) values (28, 'Most Assists', 2022, 'Record-setting assist numbers');
insert into Player_Awards (recipient, award_type, year, description) values (29, 'Best Defender', 2022, 'Elite defensive presence');
insert into Player_Awards (recipient, award_type, year, description) values (30, 'Most Improved', 2022, 'Remarkable growth and development');
insert into Player_Awards (recipient, award_type, year, description) values (31, 'Rookie of the Year', 2022, 'Exceptional rookie season');
insert into Player_Awards (recipient, award_type, year, description) values (32, 'MVP', 2021, 'Most Valuable Player - Exceptional season');
insert into Player_Awards (recipient, award_type, year, description) values (33, 'Top Scorer', 2021, 'Scoring champion');
insert into Player_Awards (recipient, award_type, year, description) values (34, 'Most Assists', 2021, 'Outstanding playmaking ability');
insert into Player_Awards (recipient, award_type, year, description) values (35, 'Best Defender', 2021, 'Elite defensive skills');
insert into Player_Awards (recipient, award_type, year, description) values (36, 'Most Improved', 2021, 'Significant development');
insert into Player_Awards (recipient, award_type, year, description) values (37, 'Rookie of the Year', 2021, 'Outstanding debut');
insert into Player_Awards (recipient, award_type, year, description) values (38, 'MVP', 2020, 'Most Valuable Player - Championship performance');
insert into Player_Awards (recipient, award_type, year, description) values (39, 'Top Scorer', 2020, 'Leading scorer');
insert into Player_Awards (recipient, award_type, year, description) values (40, 'Most Assists', 2020, 'Record-breaking assists');
insert into Player_Awards (recipient, award_type, year, description) values (41, 'Best Defender', 2020, 'Defensive player of the year');
insert into Player_Awards (recipient, award_type, year, description) values (42, 'Most Improved', 2020, 'Remarkable improvement');
insert into Player_Awards (recipient, award_type, year, description) values (43, 'Rookie of the Year', 2020, 'Exceptional rookie campaign');
insert into Player_Awards (recipient, award_type, year, description) values (44, 'Sixth Man of the Year', 2026, 'Outstanding performance off the bench');
insert into Player_Awards (recipient, award_type, year, description) values (45, 'Clutch Performer', 2026, 'Excellence in high-pressure situations');
insert into Player_Awards (recipient, award_type, year, description) values (46, 'Team Captain Award', 2026, 'Outstanding leadership and dedication');
insert into Player_Awards (recipient, award_type, year, description) values (47, 'Comeback Player', 2026, 'Remarkable return from injury');
insert into Player_Awards (recipient, award_type, year, description) values (48, 'All-Star Selection', 2026, 'Selected to represent league in all-star game');
insert into Player_Awards (recipient, award_type, year, description) values (49, 'Fan Favorite', 2026, 'Most popular player voted by fans');